"""Unit tests verifying documentation contracts and release artifacts for v0.6.1."""

from pathlib import Path


def test_v061_release_notes_draft_exists():
    release_notes = Path("docs/releases/v0.6.1.md")
    assert release_notes.exists(), "docs/releases/v0.6.1.md must exist"
    content = release_notes.read_text(encoding="utf-8")
    assert "SLR Platform v0.6.1" in content
    assert "BibTeX" in content
    assert "RIS" in content
    assert "XLSX" in content
    assert "PRISMA 2020 SVG" in content
    assert "PRISMA 2020 PDF" in content
    assert "Provenance" in content


def test_exports_prisma_specification_completeness():
    spec_path = Path("docs/EXPORTS_PRISMA.md")
    assert spec_path.exists(), "docs/EXPORTS_PRISMA.md must exist"
    content = spec_path.read_text(encoding="utf-8")

    # All 7 formats / endpoints
    assert "/exports/bibtex" in content
    assert "/exports/ris" in content
    assert "/exports/xlsx" in content
    assert "/extraction/export?format=csv" in content
    assert "/extraction/export?format=json" in content
    assert "/prisma/flow.svg" in content
    assert "/prisma/flow.pdf" in content

    # Reviewer scoping
    assert "Reviewer Scoping & Isolation" in content
    assert "reviewer_id" in content

    # Provenance headers
    assert "X-Project-Id" in content
    assert "X-Protocol-Version" in content
    assert "X-Application-Version" in content
    assert "X-Generated-At" in content

    # In-file provenance (D8)
    assert "Decision D8" in content or "D8" in content
    assert "%% Generated by SLR Platform" in content

    # Formula protection
    assert "Formula Injection" in content
    assert "Width-Aware" in content
